# Generated by Django 5.1.6 on 2025-03-30 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio en la moneda local (debe ser ≥ 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Base'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('deportivo', 'Calzado Deportivo'), ('utilitario', 'Calzado Utilitario')], help_text='Tipo de calzado según su uso principal', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detalles técnicos y características del producto', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('unisex', 'Unisex'), ('niño', 'Niño')], help_text='Público objetivo del producto', max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="Nombre comercial del artículo (ej: 'Zapato Running XYZ')", max_length=100, verbose_name='Nombre del Producto'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'gender'], name='product_category_gender_idx'),
        ),
    ]
